---
language: python

python:
  - "2.7"
  - "3.5"

services:
  - docker

before_install:
  - docker build -t php-test .
  - docker run -d -p 80:80 php-test
  - docker ps -a
  
install:
  - pip install -r requirements.txt

script:
  - python test/selenium/test1.py
  - docker ps -a
