---
services:
  - docker

before_install:
  - docker build -t zahari/php-test .
  - docker rm -f $(docker ps -a -q)
  - docker run -d -p 80:80 zahari/php-test
  - docker ps -a

script:
  - phantomjs test/test1.js
  - docker rm -f $(docker ps -a -q)
  - docker ps -a

